### ISSUE TITLE
In listView the onLoadMore function is not working

### ISSUE THREAD

**Issue by thebookofjedediah** [thebookofjedediah/react-bulletin#18]

**Comment by thebookofjedediah** [comment]
Here is an image of the issue

https://i.imgur.com/iB8G2NI.png

**Comment by thebookofjedediah** [comment]
this doesn't happen unless there are more than 15 posts, to recreate the issue switch either the post number to 5 or the link to the wpgraphql link for more posts

**Comment by pantharshit00** [comment]
I was hitting this when I was fixing something else. Already fixed now

**Comment by thebookofjedediah** [comment]
I am still getting this one. The reason you didn't was because the apolloClient was set to a WP site with less than 15 posts. 

Set the ApolloClient to the wpgraphql site, then go to uncategorized, and scroll down, this happens still

<img width="724" alt="Screen Shot 2019-07-21 at 9 04 41 AM" src="https://user-images.githubusercontent.com/37187167/61591623-c3353900-ab96-11e9-8217-715363c5840f.png">
